const adminStyles = {

  container: {
      minHeight: '100vh',
      background: 'var(--bg-app)',
      display: 'flex',
      flexDirection: 'column',
      transition: 'background-color 0.3s ease',
    },
    loading: {
      minHeight: '100vh',
      background: 'var(--bg-app)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 16,
      color: 'var(--text-secundario)',
    },
    loadingSpinner: {
      width: 40,
      height: 40,
      border: '3px solid var(--border-suave)',
      borderTopColor: 'var(--color-primario)',
      borderRadius: '50%',
      animation: 'spin 1s linear infinite',
    },
    header: {
      background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
      padding: '18px 24px',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    headerSubtitulo: {
      fontSize: 12,
      color: 'rgba(255,255,255,0.6)',
      fontWeight: 500,
      marginBottom: 2,
      letterSpacing: 0.3,
    },
    headerTitulo: {
      fontSize: 20,
      fontWeight: 700,
      color: '#fff',
      letterSpacing: '-0.02em',
    },
    headerAcciones: {
      display: 'flex',
      gap: 8,
    },
    iconBtnDark: {
      width: 40,
      height: 40,
      borderRadius: 'var(--radius-full)',
      background: 'rgba(255,255,255,0.1)',
      border: '1px solid rgba(255,255,255,0.15)',
      color: '#fff',
      fontSize: 16,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
    },
    btnSalir: {
      width: 40,
      height: 40,
      background: 'rgba(239, 68, 68, 0.2)',
      color: '#fff',
      border: '1px solid rgba(239, 68, 68, 0.3)',
      borderRadius: 'var(--radius-full)',
      fontSize: 16,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabs: {
      display: 'flex',
      background: 'var(--bg-card)',
      padding: '8px 8px 0',
      gap: 4,
      borderBottom: '1px solid var(--border-suave)',
      overflowX: 'auto',
      scrollbarWidth: 'none',
    },
    tab: {
      flex: 1,
      minWidth: 70,
      padding: '10px 6px',
      border: 'none',
      background: 'transparent',
      fontSize: 12,
      color: 'var(--text-suave)',
      fontWeight: 600,
      cursor: 'pointer',
      borderBottom: '2.5px solid transparent',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      transition: 'all 0.2s ease',
    },
    tabActivo: {
      color: 'var(--color-primario)',
      borderBottomColor: 'var(--color-primario)',
    },
    tabIcon: {
      fontSize: 16,
    },
    tabLabel: {
      fontSize: 11,
    },
    mensajeGlobal: {
      padding: '10px 16px',
      textAlign: 'center',
      fontSize: 13,
      fontWeight: 600,
      background: 'rgba(16, 185, 129, 0.1)',
      color: 'var(--color-exito)',
      borderBottom: '1px solid rgba(16, 185, 129, 0.2)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    mensajeIcon: {
      fontSize: 14,
    },
    content: {
      flex: 1,
      padding: '20px 18px 40px',
    },
    tabContent: {
      display: 'flex',
      flexDirection: 'column',
      gap: 14,
    },
    carruselContainer: {
      position: 'relative',
      width: '100%',
      aspectRatio: '16/10',
      maxHeight: 280,
      background: '#000',
      borderRadius: 'var(--radius-lg)',
      overflow: 'hidden',
    },
    carruselImg: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      cursor: 'pointer',
    },
    carruselBtn: {
      position: 'absolute',
      top: '50%',
      transform: 'translateY(-50%)',
      background: 'rgba(0,0,0,0.5)',
      backdropFilter: 'blur(10px)',
      color: '#fff',
      border: 'none',
      borderRadius: 'var(--radius-full)',
      width: 36,
      height: 36,
      fontSize: 20,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    carruselIndicadores: {
      position: 'absolute',
      bottom: 12,
      left: 0,
      right: 0,
      display: 'flex',
      justifyContent: 'center',
      gap: 6,
    },
    indicador: {
      height: 8,
      borderRadius: 'var(--radius-full)',
      cursor: 'pointer',
      transition: 'all 0.3s ease',
    },
    miniaturasContainer: {
      display: 'flex',
      gap: 8,
      paddingBottom: 4,
      overflowX: 'auto',
      scrollbarWidth: 'none',
    },
    miniatura: {
      width: 56,
      height: 56,
      objectFit: 'cover',
      borderRadius: 'var(--radius-sm)',
      cursor: 'pointer',
      flexShrink: 0,
      transition: 'all 0.2s ease',
    },
    sinFotos: {
      width: '100%',
      height: 180,
      background: 'var(--bg-card)',
      border: '1px dashed var(--border-medio)',
      borderRadius: 'var(--radius-lg)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      color: 'var(--text-suave)',
      fontSize: 14,
    },
    card: {
      background: 'var(--bg-card)',
      borderRadius: 'var(--radius-lg)',
      padding: '16px 18px',
      border: '1px solid var(--border-suave)',
      boxShadow: 'var(--shadow-sm)',
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
    },
    cardHeaderRow: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 12,
    },
    cardTitulo: {
      fontSize: 15,
      fontWeight: 700,
      color: 'var(--text-principal)',
      letterSpacing: '-0.01em',
    },
    cardTituloGrande: {
      fontSize: 18,
      fontWeight: 700,
      color: 'var(--text-principal)',
      letterSpacing: '-0.02em',
      marginBottom: 4,
    },
    cardSubtitulo: {
      fontSize: 12,
      color: 'var(--text-suave)',
      marginTop: 2,
    },
    cardSub: {
      fontSize: 13,
      color: 'var(--text-secundario)',
      lineHeight: 1.5,
    },
    cardIcono: {
      width: 40,
      height: 40,
      borderRadius: 'var(--radius-full)',
      background: 'linear-gradient(135deg, var(--color-primario) 0%, var(--color-primario-hover) 100%)',
      color: '#fff',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontWeight: 700,
      fontSize: 16,
      flexShrink: 0,
      boxShadow: '0 4px 8px rgba(79, 70, 229, 0.2)',
    },
    categoriaBadge: {
      display: 'inline-block',
      background: 'var(--color-primario-suave)',
      color: 'var(--color-primario)',
      border: '1px solid var(--color-primario-borde)',
      fontSize: 11,
      fontWeight: 700,
      padding: '4px 10px',
      borderRadius: 'var(--radius-full)',
      textTransform: 'capitalize',
    },
    infoLista: {
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
      marginTop: 4,
    },
    infoItem: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      padding: '8px 0',
    },
    infoIcon: {
      fontSize: 14,
      width: 24,
      textAlign: 'center',
    },
    infoTexto: {
      fontSize: 13,
      color: 'var(--text-secundario)',
    },
    inputGroup: {
      display: 'flex',
      flexDirection: 'column',
      gap: 6,
    },
    inputsRow: {
      display: 'flex',
      gap: 8,
      flexWrap: 'wrap',
    },
    label: {
      fontSize: 12,
      fontWeight: 600,
      color: 'var(--text-secundario)',
    },
    input: {
      padding: '11px 14px',
      borderRadius: 'var(--radius-sm)',
      border: '1.5px solid var(--border-suave)',
      background: 'var(--bg-input)',
      color: 'var(--text-principal)',
      fontSize: 14,
      width: '100%',
    },
    inputSmall: {
      padding: '9px 12px',
      borderRadius: 'var(--radius-sm)',
      border: '1.5px solid var(--border-suave)',
      background: 'var(--bg-input)',
      color: 'var(--text-principal)',
      fontSize: 13,
      flex: 1,
      minWidth: 80,
    },
    textarea: {
      padding: '11px 14px',
      borderRadius: 'var(--radius-sm)',
      border: '1.5px solid var(--border-suave)',
      background: 'var(--bg-input)',
      color: 'var(--text-principal)',
      fontSize: 14,
      minHeight: 80,
      resize: 'vertical',
      fontFamily: 'inherit',
    },
    hint: {
      fontSize: 11,
      color: 'var(--text-suave)',
      textAlign: 'center',
    },
    botonesRow: {
      display: 'flex',
      gap: 8,
    },
    btnEditar: {
      background: 'var(--bg-hover)',
      border: '1px solid var(--border-suave)',
      borderRadius: 'var(--radius-sm)',
      padding: '7px 14px',
      cursor: 'pointer',
      fontSize: 12,
      fontWeight: 600,
      color: 'var(--text-secundario)',
    },
    btnGuardar: {
      flex: 1,
      padding: '11px',
      borderRadius: 'var(--radius-sm)',
      border: 'none',
      background: 'var(--color-primario)',
      color: '#fff',
      fontSize: 13,
      fontWeight: 600,
      cursor: 'pointer',
    },
    btnCancelar: {
      flex: 1,
      padding: '11px',
      borderRadius: 'var(--radius-sm)',
      border: '1px solid var(--border-suave)',
      background: 'transparent',
      color: 'var(--text-secundario)',
      fontSize: 13,
      fontWeight: 600,
      cursor: 'pointer',
    },
    btnGuardarSmall: {
      padding: '7px 11px',
      borderRadius: 'var(--radius-sm)',
      border: 'none',
      background: 'rgba(16, 185, 129, 0.15)',
      color: 'var(--color-exito)',
      fontWeight: 600,
      cursor: 'pointer',
      fontSize: 12,
    },
    btnCancelarSmall: {
      padding: '7px 11px',
      borderRadius: 'var(--radius-sm)',
      border: 'none',
      background: 'rgba(239, 68, 68, 0.15)',
      color: 'var(--color-error)',
      fontWeight: 600,
      cursor: 'pointer',
      fontSize: 12,
    },
    btnAgregar: {
      padding: '11px',
      borderRadius: 'var(--radius-sm)',
      border: 'none',
      background: 'var(--color-primario)',
      color: '#fff',
      fontSize: 13,
      fontWeight: 600,
      cursor: 'pointer',
    },
    btnAprobar: {
      padding: '8px 14px',
      borderRadius: 'var(--radius-sm)',
      border: '1px solid rgba(16, 185, 129, 0.2)',
      background: 'rgba(16, 185, 129, 0.1)',
      color: 'var(--color-exito)',
      fontWeight: 600,
      cursor: 'pointer',
      fontSize: 12,
      flex: 1,
    },
    btnRechazar: {
      padding: '8px 14px',
      borderRadius: 'var(--radius-sm)',
      border: '1px solid rgba(239, 68, 68, 0.2)',
      background: 'rgba(239, 68, 68, 0.1)',
      color: 'var(--color-error)',
      fontWeight: 600,
      cursor: 'pointer',
      fontSize: 12,
      flex: 1,
    },
    btnPeligro: {
      padding: '10px 14px',
      borderRadius: 'var(--radius-sm)',
      border: '1px solid rgba(239, 68, 68, 0.2)',
      background: 'rgba(239, 68, 68, 0.1)',
      color: 'var(--color-error)',
      fontWeight: 600,
      cursor: 'pointer',
      fontSize: 13,
      flex: 1,
    },
    btnAprobarPeq: {
      padding: '6px 12px',
      borderRadius: 'var(--radius-full)',
      border: '1px solid rgba(16, 185, 129, 0.2)',
      background: 'rgba(16, 185, 129, 0.1)',
      color: 'var(--color-exito)',
      fontWeight: 600,
      cursor: 'pointer',
      fontSize: 11,
    },
    btnRechazarPeq: {
      padding: '6px 12px',
      borderRadius: 'var(--radius-full)',
      border: '1px solid rgba(239, 68, 68, 0.2)',
      background: 'rgba(239, 68, 68, 0.1)',
      color: 'var(--color-error)',
      fontWeight: 600,
      cursor: 'pointer',
      fontSize: 11,
    },
    acciones: {
      display: 'flex',
      gap: 8,
      marginTop: 4,
    },
    diaCard: {
      background: 'var(--bg-card)',
      borderRadius: 'var(--radius-md)',
      overflow: 'hidden',
      border: '1px solid var(--border-suave)',
      boxShadow: 'var(--shadow-sm)',
    },
    diaHeader: {
      padding: '14px 16px',
      display: 'flex',
      alignItems: 'center',
      gap: 12,
      cursor: 'pointer',
      transition: 'background 0.2s ease',
    },
    diaNombreWrap: {
      display: 'flex',
      flexDirection: 'column',
      width: 90,
      flexShrink: 0,
    },
    diaNombre: {
      fontSize: 14,
      fontWeight: 700,
      color: 'var(--text-principal)',
      letterSpacing: '-0.01em',
    },
    diaFecha: {
      fontSize: 11,
      color: 'var(--text-suave)',
      fontWeight: 500,
      marginTop: 2,
    },
    horariosResumen: {
      display: 'flex',
      gap: 6,
      flexWrap: 'wrap',
      flex: 1,
    },
    horarioBadge: {
      background: 'var(--color-primario-suave)',
      color: 'var(--color-primario)',
      border: '1px solid var(--color-primario-borde)',
      fontSize: 11,
      fontWeight: 700,
      padding: '4px 9px',
      borderRadius: 'var(--radius-full)',
    },
    cerradoBadge: {
      background: 'var(--bg-hover)',
      color: 'var(--text-suave)',
      fontSize: 11,
      fontWeight: 600,
      padding: '4px 9px',
      borderRadius: 'var(--radius-full)',
      border: '1px solid var(--border-suave)',
    },
    chevron: {
      marginLeft: 'auto',
      color: 'var(--text-suave)',
      fontSize: 11,
    },
    diaDetalle: {
      borderTop: '1px solid var(--border-suave)',
      padding: '14px 16px',
      display: 'flex',
      flexDirection: 'column',
      gap: 10,
    },
    horarioRow: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      background: 'var(--bg-hover)',
      borderRadius: 'var(--radius-sm)',
      padding: '10px 12px',
      flexWrap: 'wrap',
    },
    horarioRowConBoton: {
      display: 'flex',
      flexDirection: 'column',
      gap: 6,
    },
    btnVerInscritos: {
      background: 'var(--color-primario-suave)',
      border: '1px solid var(--color-primario-borde)',
      borderRadius: 'var(--radius-sm)',
      padding: '8px 12px',
      color: 'var(--color-primario)',
      fontSize: 12,
      fontWeight: 600,
      cursor: 'pointer',
      textAlign: 'center',
    },
    editRow: {
      display: 'flex',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
      background: 'rgba(245, 158, 11, 0.08)',
      border: '1px solid rgba(245, 158, 11, 0.2)',
      borderRadius: 'var(--radius-sm)',
      padding: '10px 12px',
    },
    horarioTexto: {
      fontSize: 13,
      fontWeight: 700,
      color: 'var(--color-primario)',
      flex: 1,
    },
    cuposTexto: {
      fontSize: 12,
      color: 'var(--text-secundario)',
    },
    btnEditarHorario: {
      padding: '6px 11px',
      borderRadius: 'var(--radius-sm)',
      border: '1px solid var(--color-primario-borde)',
      background: 'var(--color-primario-suave)',
      color: 'var(--color-primario)',
      fontWeight: 600,
      cursor: 'pointer',
      fontSize: 11,
    },
    btnEliminarHorario: {
      padding: '6px 11px',
      borderRadius: 'var(--radius-sm)',
      border: '1px solid rgba(239, 68, 68, 0.2)',
      background: 'rgba(239, 68, 68, 0.1)',
      color: 'var(--color-error)',
      fontWeight: 600,
      cursor: 'pointer',
      fontSize: 11,
    },
    btnCopiar: {
      background: 'var(--color-primario-suave)',
      border: '1px dashed var(--color-primario)',
      borderRadius: 'var(--radius-sm)',
      padding: '10px',
      color: 'var(--color-primario)',
      fontSize: 12,
      fontWeight: 600,
      cursor: 'pointer',
      textAlign: 'center',
    },
    agregarHorario: {
      background: 'var(--color-primario-suave)',
      border: '1px solid var(--color-primario-borde)',
      borderRadius: 'var(--radius-sm)',
      padding: '12px',
      display: 'flex',
      flexDirection: 'column',
      gap: 10,
    },
    agregarTitulo: {
      fontSize: 13,
      fontWeight: 700,
      color: 'var(--color-primario)',
    },
    motivoBox: {
      borderRadius: 'var(--radius-sm)',
      padding: '10px 12px',
      fontSize: 12,
      fontWeight: 600,
    },
    searchBoxAdmin: {
      display: 'flex',
      alignItems: 'center',
      background: 'var(--bg-card)',
      borderRadius: 'var(--radius-md)',
      padding: '10px 14px',
      border: '1px solid var(--border-suave)',
      boxShadow: 'var(--shadow-sm)',
      gap: 10,
    },
    searchInputAdmin: {
      flex: 1,
      border: 'none',
      outline: 'none',
      fontSize: 13,
      color: 'var(--text-principal)',
      background: 'transparent',
    },
    clearBtnAdmin: {
      background: 'var(--bg-hover)',
      border: 'none',
      color: 'var(--text-suave)',
      cursor: 'pointer',
      fontSize: 11,
      width: 22,
      height: 22,
      borderRadius: 'var(--radius-full)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    vacio: {
      textAlign: 'center',
      padding: '40px 20px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: 12,
      background: 'var(--bg-card)',
      border: '1px solid var(--border-suave)',
      borderRadius: 'var(--radius-lg)',
    },
    vacioIcon: {
      fontSize: 48,
      opacity: 0.5,
    },
    vacioTexto: {
      fontSize: 14,
      color: 'var(--text-secundario)',
    },
    vacioTextoCentrado: {
      fontSize: 13,
      color: 'var(--text-suave)',
      textAlign: 'center',
      padding: '16px 0',
    },
    badge: {
      alignSelf: 'flex-start',
      padding: '5px 11px',
      borderRadius: 'var(--radius-full)',
      fontSize: 11,
      fontWeight: 700,
      border: '1px solid',
      textTransform: 'capitalize',
    },
    btnEspecial: {
      background: 'rgba(245, 158, 11, 0.1)',
      border: '1px dashed var(--color-advertencia)',
      borderRadius: 'var(--radius-md)',
      padding: '14px',
      color: 'var(--color-advertencia)',
      fontSize: 14,
      fontWeight: 700,
      cursor: 'pointer',
      textAlign: 'center',
    },
    modalOverlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'rgba(0,0,0,0.6)',
      backdropFilter: 'blur(4px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 100,
      padding: '20px',
    },
    modal: {
      background: 'var(--bg-card)',
      borderRadius: 'var(--radius-xl)',
      padding: '24px',
      width: '100%',
      maxWidth: 440,
      maxHeight: '85vh',
      overflowY: 'auto',
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
      border: '1px solid var(--border-suave)',
      boxShadow: 'var(--shadow-lg)',
    },
    modalIconWarn: {
      width: 48,
      height: 48,
      borderRadius: 'var(--radius-full)',
      background: 'rgba(239, 68, 68, 0.1)',
      color: 'var(--color-error)',
      fontSize: 24,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      margin: '0 auto',
    },
    modalHeaderInscritos: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 8,
      paddingBottom: 8,
      borderBottom: '1px solid var(--border-suave)',
    },
    btnCerrarModal: {
      background: 'var(--bg-hover)',
      border: '1px solid var(--border-suave)',
      color: 'var(--text-secundario)',
      fontSize: 14,
      fontWeight: 700,
      width: 32,
      height: 32,
      borderRadius: 'var(--radius-full)',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    contadorInscritos: {
      background: 'var(--color-primario-suave)',
      border: '1px solid var(--color-primario-borde)',
      borderRadius: 'var(--radius-md)',
      padding: '12px 16px',
      display: 'flex',
      alignItems: 'center',
      gap: 12,
    },
    contadorNumero: {
      fontSize: 28,
      fontWeight: 700,
      color: 'var(--color-primario)',
      letterSpacing: '-0.02em',
    },
    contadorTexto: {
      fontSize: 12,
      color: 'var(--text-secundario)',
      fontWeight: 500,
    },
    listaInscritos: {
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
      maxHeight: 300,
      overflowY: 'auto',
    },
    diaBadge: {
      padding: '10px 16px',
      borderRadius: 'var(--radius-full)',
      border: '1px solid',
      cursor: 'pointer',
      fontSize: 12,
      fontWeight: 600,
      transition: 'all 0.2s ease',
    },
    tipoEspecialRow: {
      display: 'flex',
      gap: 8,
      flexWrap: 'wrap',
    },
    horarioEspecialItem: {
      display: 'flex',
      gap: 6,
      alignItems: 'center',
      flexWrap: 'wrap',
      background: 'var(--bg-hover)',
      border: '1px solid var(--border-suave)',
      padding: 10,
      borderRadius: 'var(--radius-sm)',
    },
    checkboxLista: {
      display: 'flex',
      flexDirection: 'column',
      gap: 6,
      marginBottom: 4,
    },
    checkboxItem: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      fontSize: 13,
      cursor: 'pointer',
      padding: '10px 12px',
      borderRadius: 'var(--radius-sm)',
      border: '1px solid',
      transition: 'all 0.2s ease',
    },
    diasGrid: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 6,
      marginBottom: 4,
    },
    errorTexto: {
      fontSize: 12,
      color: 'var(--color-error)',
      fontWeight: 600,
      textAlign: 'center',
      padding: '8px 0',
    },
    exitoTexto: {
      fontSize: 12,
      color: 'var(--color-exito)',
      fontWeight: 600,
      textAlign: 'center',
      padding: '4px 0',
    },
    exitoBox: {
      background: 'rgba(16, 185, 129, 0.1)',
      color: 'var(--color-exito)',
      border: '1px solid rgba(16, 185, 129, 0.2)',
      borderRadius: 'var(--radius-sm)',
      padding: '12px',
      fontSize: 13,
      fontWeight: 600,
      textAlign: 'center',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    excepcionCard: {
      borderRadius: 'var(--radius-sm)',
      padding: '12px',
      border: '1px solid',
      display: 'flex',
      flexDirection: 'column',
      gap: 6,
    },
    excepcionHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    excepcionFecha: {
      fontSize: 13,
      fontWeight: 700,
      color: 'var(--text-principal)',
      textTransform: 'capitalize',
    },
    excepcionHorarios: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 6,
    },
    excepcionMotivo: {
      fontSize: 11,
      color: 'var(--text-suave)',
      fontStyle: 'italic',
    },
    galeriaSeccion: {
      borderTop: '1px solid var(--border-suave)',
      paddingTop: 14,
      marginTop: 4,
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
    },
    galeriaTitulo: {
      fontSize: 13,
      fontWeight: 700,
      color: 'var(--text-principal)',
    },
    galeriaSubtitulo: {
      fontSize: 12,
      color: 'var(--text-secundario)',
    },
    galeriaVacia: {
      fontSize: 12,
      color: 'var(--text-suave)',
      textAlign: 'center',
      padding: '8px 0',
    },
    galeriaGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(90px, 1fr))',
      gap: 8,
      marginTop: 4,
    },
    galeriaFotoItem: {
      position: 'relative',
      borderRadius: 'var(--radius-sm)',
      overflow: 'hidden',
      aspectRatio: '1',
      background: 'var(--bg-hover)',
      border: '1px solid var(--border-suave)',
    },
    btnEliminarFoto: {
      position: 'absolute',
      top: 4,
      right: 4,
      background: 'rgba(239, 68, 68, 0.9)',
      color: '#fff',
      border: 'none',
      borderRadius: 'var(--radius-full)',
      width: 22,
      height: 22,
      cursor: 'pointer',
      fontSize: 10,
      fontWeight: 700,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    horarioActivoHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      flexWrap: 'wrap',
      gap: 8,
    },
    horarioActivoBotones: {
      display: 'flex',
      gap: 6,
    },
    personaRow: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      background: 'var(--bg-hover)',
      borderRadius: 'var(--radius-sm)',
      padding: '10px 12px',
      flexWrap: 'wrap',
    },
    saldoCard: {
      background: 'rgba(239, 68, 68, 0.05)',
      borderRadius: 'var(--radius-sm)',
      padding: '12px',
      display: 'flex',
      flexDirection: 'column',
      gap: 10,
      border: '1px solid rgba(239, 68, 68, 0.15)',
    },
    saldoCardHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
    },
    pagoParcialRow: {
      display: 'flex',
      gap: 8,
      alignItems: 'center',
    },
    perfilContainer: {
      display: 'flex',
      flexDirection: 'column',
      gap: 16,
      alignItems: 'center',
    },
    avatarSeccion: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: 10,
      marginTop: 8,
    },
    avatar: {
      width: 88,
      height: 88,
      borderRadius: 'var(--radius-full)',
      background: 'linear-gradient(135deg, var(--color-primario) 0%, var(--color-primario-hover) 100%)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      boxShadow: '0 10px 30px rgba(79, 70, 229, 0.35)',
    },
    avatarLetra: {
      fontSize: 38,
      color: '#fff',
      fontWeight: 700,
      letterSpacing: '-0.02em',
    },
    nombre: {
      fontSize: 20,
      fontWeight: 700,
      color: 'var(--text-principal)',
      letterSpacing: '-0.02em',
    },
    rolBadge: {
      display: 'flex',
      alignItems: 'center',
      gap: 6,
      padding: '6px 12px',
      background: 'var(--color-primario-suave)',
      border: '1px solid var(--color-primario-borde)',
      borderRadius: 'var(--radius-full)',
      fontSize: 12,
      fontWeight: 600,
      color: 'var(--color-primario)',
    },
    formGroup: {
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
    },
    infoBoxNoEditable: {
      background: 'var(--bg-hover)',
      borderRadius: 'var(--radius-sm)',
      padding: '11px 14px',
      border: '1px solid var(--border-suave)',
    },
    infoBoxLabel: {
      fontSize: 11,
      color: 'var(--text-suave)',
      fontWeight: 600,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    infoBoxValor: {
      fontSize: 14,
      color: 'var(--text-secundario)',
      marginTop: 4,
    },
    infoLista2: {
      display: 'flex',
      flexDirection: 'column',
    },
    infoRow2: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottom: '1px solid var(--border-suave)',
      padding: '11px 0',
    },
    infoLabel2: {
      fontSize: 13,
      color: 'var(--text-secundario)',
    },
    infoValor2: {
      fontSize: 14,
      fontWeight: 600,
      color: 'var(--text-principal)',
    },
    infoValor2Pequeno: {
      fontSize: 13,
      fontWeight: 600,
      color: 'var(--text-principal)',
    },
    passDisplay: {
      padding: '14px 16px',
      background: 'var(--bg-hover)',
      borderRadius: 'var(--radius-sm)',
      border: '1px solid var(--border-suave)',
    },
    passDots: {
      fontSize: 18,
      color: 'var(--text-suave)',
      letterSpacing: 4,
    },
    lightboxOverlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'rgba(0,0,0,0.95)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 200,
      cursor: 'pointer',
    },
    lightboxImg: {
      maxWidth: '95%',
      maxHeight: '85%',
      objectFit: 'contain',
      cursor: 'default',
      borderRadius: 'var(--radius-md)',
    },
    lightboxCerrar: {
      position: 'absolute',
      top: 16,
      right: 16,
      background: 'rgba(255,255,255,0.15)',
      backdropFilter: 'blur(10px)',
      color: '#fff',
      border: '1px solid rgba(255,255,255,0.2)',
      fontSize: 18,
      fontWeight: 700,
      width: 44,
      height: 44,
      borderRadius: 'var(--radius-full)',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    lightboxNav: {
      position: 'absolute',
      top: '50%',
      transform: 'translateY(-50%)',
      background: 'rgba(255,255,255,0.15)',
      backdropFilter: 'blur(10px)',
      color: '#fff',
      border: '1px solid rgba(255,255,255,0.2)',
      fontSize: 28,
      fontWeight: 700,
      width: 52,
      height: 52,
      borderRadius: 'var(--radius-full)',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    lightboxContador: {
      position: 'absolute',
      bottom: 24,
      color: '#fff',
      fontSize: 13,
      fontWeight: 600,
      background: 'rgba(0,0,0,0.5)',
      padding: '6px 14px',
      borderRadius: 'var(--radius-full)',
    },
  };

export default adminStyles;
