const styles = {
  container: {
    minHeight: '100vh',
    background: 'var(--bg-app)',
    transition: 'background-color 0.3s ease',
  },
  loading: {
    minHeight: '100vh',
    background: 'var(--bg-app)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    color: 'var(--text-secundario)',
  },
  loadingSpinner: {
    width: 40,
    height: 40,
    border: '3px solid var(--border-suave)',
    borderTopColor: 'var(--color-primario)',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  toast: {
    position: 'fixed',
    top: 20,
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 999,
    padding: '12px 20px',
    borderRadius: 'var(--radius-md)',
    color: '#fff',
    fontSize: 14,
    fontWeight: 600,
    boxShadow: 'var(--shadow-lg)',
    maxWidth: '90%',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  toastIcon: {
    fontSize: 16,
  },
  header: {
    background: 'var(--bg-card)',
    padding: '14px 20px',
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    borderBottom: '1px solid var(--border-suave)',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  btnVolver: {
    width: 40,
    height: 40,
    borderRadius: 'var(--radius-full)',
    background: 'var(--bg-hover)',
    border: '1px solid var(--border-suave)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 18,
    color: 'var(--text-principal)',
    fontWeight: 700,
  },
  btnVolverIcon: {
    fontSize: 18,
  },
  headerTitulo: {
    flex: 1,
    fontSize: 17,
    fontWeight: 700,
    color: 'var(--text-principal)',
    letterSpacing: '-0.01em',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 'var(--radius-full)',
    background: 'var(--bg-hover)',
    border: '1px solid var(--border-suave)',
    fontSize: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  carruselContainer: {
    position: 'relative',
    width: '100%',
    aspectRatio: '16/10',
    maxHeight: 400,
    background: '#000',
    overflow: 'hidden',
  },
  carruselImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    cursor: 'pointer',
  },
  carruselBtn: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'rgba(0,0,0,0.5)',
    backdropFilter: 'blur(10px)',
    color: '#fff',
    border: 'none',
    borderRadius: 'var(--radius-full)',
    width: 40,
    height: 40,
    fontSize: 22,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  carruselIndicadores: {
    position: 'absolute',
    bottom: 14,
    left: 0,
    right: 0,
    display: 'flex',
    justifyContent: 'center',
    gap: 6,
  },
  indicador: {
    height: 8,
    borderRadius: 'var(--radius-full)',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  miniaturasContainer: {
    display: 'flex',
    gap: 8,
    padding: '12px 20px 0',
    overflowX: 'auto',
    scrollbarWidth: 'none',
  },
  miniatura: {
    width: 60,
    height: 60,
    objectFit: 'cover',
    borderRadius: 'var(--radius-sm)',
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'all 0.2s ease',
  },
  content: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    paddingBottom: '40px',
  },
  infoLugar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  titulo: {
    fontSize: 24,
    fontWeight: 700,
    color: 'var(--text-principal)',
    letterSpacing: '-0.02em',
  },
  categoriaBadge: {
    background: 'var(--color-primario-suave)',
    color: 'var(--color-primario)',
    border: '1px solid var(--color-primario-borde)',
    fontSize: 11,
    fontWeight: 700,
    padding: '5px 11px',
    borderRadius: 'var(--radius-full)',
    textTransform: 'capitalize',
  },
  desc: {
    fontSize: 14,
    color: 'var(--text-secundario)',
    lineHeight: 1.6,
  },
  contactSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  contactRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    background: 'var(--bg-card)',
    borderRadius: 'var(--radius-md)',
    padding: '12px 14px',
    cursor: 'pointer',
    border: '1px solid var(--border-suave)',
    boxShadow: 'var(--shadow-sm)',
    transition: 'all 0.2s ease',
  },
  iconBoxWrap: {
    width: 40,
    height: 40,
    borderRadius: 'var(--radius-md)',
    background: 'var(--color-primario-suave)',
    border: '1px solid var(--color-primario-borde)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  iconBox: {
    fontSize: 18,
  },
  contactLabel: {
    fontSize: 11,
    color: 'var(--text-suave)',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  contactValor: {
    fontSize: 14,
    color: 'var(--text-principal)',
    fontWeight: 600,
    marginTop: 2,
  },
  flecha: {
    color: 'var(--text-suave)',
    fontSize: 18,
  },
  horariosSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    marginTop: 8,
  },
  subtitulo: {
    fontSize: 18,
    fontWeight: 700,
    color: 'var(--text-principal)',
    letterSpacing: '-0.01em',
    marginBottom: 4,
  },
  diaCard: {
    background: 'var(--bg-card)',
    borderRadius: 'var(--radius-md)',
    padding: '14px 16px',
    border: '1px solid var(--border-suave)',
    boxShadow: 'var(--shadow-sm)',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  diaHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  diaNombre: {
    fontSize: 15,
    fontWeight: 700,
    color: 'var(--text-principal)',
    textTransform: 'capitalize',
    letterSpacing: '-0.01em',
  },
  diaFecha: {
    fontSize: 12,
    color: 'var(--text-suave)',
    marginTop: 2,
    textTransform: 'capitalize',
  },
  cerradoBadge: {
    background: 'rgba(239, 68, 68, 0.1)',
    color: 'var(--color-error)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    fontSize: 11,
    fontWeight: 700,
    padding: '5px 11px',
    borderRadius: 'var(--radius-full)',
  },
  especialBadge: {
    background: 'rgba(245, 158, 11, 0.1)',
    color: 'var(--color-advertencia)',
    border: '1px solid rgba(245, 158, 11, 0.2)',
    fontSize: 11,
    fontWeight: 700,
    padding: '5px 11px',
    borderRadius: 'var(--radius-full)',
  },
  sinHorarioBadge: {
    background: 'var(--bg-hover)',
    color: 'var(--text-suave)',
    fontSize: 11,
    fontWeight: 600,
    padding: '5px 11px',
    borderRadius: 'var(--radius-full)',
    border: '1px solid var(--border-suave)',
  },
  horariosList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  horarioItem: {
    borderRadius: 'var(--radius-md)',
    padding: '12px 14px',
    border: '1px solid',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  horarioInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  horarioTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  horarioHora: {
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: '-0.01em',
  },
  horarioEstado: {
    fontSize: 11,
    color: 'var(--text-suave)',
    fontWeight: 600,
  },
  cuposRow: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
  },
  cuposBadge: {
    fontSize: 12,
    color: 'var(--text-secundario)',
    background: 'var(--bg-hover)',
    padding: '4px 10px',
    borderRadius: 'var(--radius-full)',
    fontWeight: 600,
  },
  tipoCanchaBadge: {
    fontSize: 11,
    color: 'var(--color-primario)',
    background: 'var(--color-primario-suave)',
    border: '1px solid var(--color-primario-borde)',
    padding: '4px 10px',
    borderRadius: 'var(--radius-full)',
    fontWeight: 700,
  },
  horarioBotones: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
  },
  sinHorarioTexto: {
    fontSize: 13,
    color: 'var(--text-suave)',
    textAlign: 'center',
    padding: '8px 0',
    fontStyle: 'italic',
  },
  motivoBox: {
    fontSize: 12,
    color: 'var(--text-secundario)',
    fontStyle: 'italic',
    background: 'var(--bg-hover)',
    padding: '8px 12px',
    borderRadius: 'var(--radius-sm)',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  btnReservar: {
    background: 'var(--color-primario)',
    color: '#fff',
    fontSize: 12,
    fontWeight: 600,
    padding: '7px 16px',
    borderRadius: 'var(--radius-full)',
    cursor: 'pointer',
    border: 'none',
  },
  btnVerPersonas: {
    background: 'var(--color-primario-suave)',
    color: 'var(--color-primario)',
    border: '1px solid var(--color-primario-borde)',
    fontSize: 12,
    fontWeight: 600,
    padding: '7px 14px',
    borderRadius: 'var(--radius-full)',
    cursor: 'pointer',
  },
  btnCancelar: {
    background: 'rgba(239, 68, 68, 0.1)',
    color: 'var(--color-error)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    fontSize: 12,
    fontWeight: 600,
    padding: '7px 14px',
    borderRadius: 'var(--radius-full)',
    cursor: 'pointer',
  },
  btnPasado: {
    background: 'var(--bg-hover)',
    color: 'var(--text-suave)',
    fontSize: 12,
    fontWeight: 600,
    padding: '7px 14px',
    borderRadius: 'var(--radius-full)',
    border: '1px solid var(--border-suave)',
  },
  btnInscribirse: {
    background: 'var(--color-primario)',
    color: '#fff',
    border: 'none',
    borderRadius: 'var(--radius-md)',
    padding: '15px',
    fontSize: 15,
    fontWeight: 700,
    cursor: 'pointer',
    marginTop: 8,
    boxShadow: '0 4px 16px rgba(79, 70, 229, 0.3)',
    transition: 'all 0.2s ease',
  },
  inscritoBadge: {
    background: 'rgba(16, 185, 129, 0.1)',
    color: 'var(--color-exito)',
    border: '1px solid rgba(16, 185, 129, 0.2)',
    borderRadius: 'var(--radius-md)',
    padding: '15px',
    fontSize: 14,
    fontWeight: 700,
    textAlign: 'center',
    marginTop: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  pendienteBadge: {
    background: 'rgba(245, 158, 11, 0.1)',
    color: 'var(--color-advertencia)',
    border: '1px solid rgba(245, 158, 11, 0.2)',
    borderRadius: 'var(--radius-md)',
    padding: '15px',
    fontSize: 14,
    fontWeight: 700,
    textAlign: 'center',
    marginTop: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  rechazadoBadge: {
    background: 'rgba(239, 68, 68, 0.1)',
    color: 'var(--color-error)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    borderRadius: 'var(--radius-md)',
    padding: '15px',
    fontSize: 14,
    fontWeight: 700,
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  badgeIcon: {
    fontSize: 16,
  },
  // Modal
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.6)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: '20px',
  },
  modal: {
    background: 'var(--bg-card)',
    borderRadius: 'var(--radius-xl)',
    padding: '24px',
    width: '100%',
    maxWidth: 440,
    maxHeight: '85vh',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    border: '1px solid var(--border-suave)',
    boxShadow: 'var(--shadow-lg)',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  modalTitulo: {
    fontSize: 17,
    fontWeight: 700,
    color: 'var(--text-principal)',
    letterSpacing: '-0.01em',
  },
  modalSub: {
    fontSize: 13,
    color: 'var(--text-secundario)',
    marginTop: 4,
    textTransform: 'capitalize',
  },
  modalSubHora: {
    fontSize: 13,
    color: 'var(--color-primario)',
    fontWeight: 600,
    marginTop: 2,
  },
  btnCerrarX: {
    width: 32,
    height: 32,
    borderRadius: 'var(--radius-full)',
    background: 'var(--bg-hover)',
    border: 'none',
    fontSize: 14,
    color: 'var(--text-secundario)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  modalContador: {
    background: 'var(--color-primario-suave)',
    border: '1px solid var(--color-primario-borde)',
    borderRadius: 'var(--radius-md)',
    padding: '12px 14px',
    display: 'flex',
    alignItems: 'baseline',
    gap: 8,
  },
  modalContadorNum: {
    fontSize: 24,
    fontWeight: 800,
    color: 'var(--color-primario)',
    letterSpacing: '-0.02em',
  },
  modalContadorTexto: {
    fontSize: 13,
    color: 'var(--text-secundario)',
    fontWeight: 500,
  },
  modalVacio: {
    textAlign: 'center',
    padding: '24px 0',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
  },
  modalVacioTexto: {
    fontSize: 13,
    color: 'var(--text-suave)',
  },
  modalLista: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    maxHeight: 280,
    overflowY: 'auto',
  },
  modalPersona: {
    background: 'var(--bg-hover)',
    border: '1px solid var(--border-suave)',
    borderRadius: 'var(--radius-md)',
    padding: '10px 14px',
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  modalAvatar: {
    width: 36,
    height: 36,
    borderRadius: 'var(--radius-full)',
    background: 'linear-gradient(135deg, var(--color-primario) 0%, var(--color-primario-hover) 100%)',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: 14,
    boxShadow: '0 4px 8px rgba(79, 70, 229, 0.2)',
  },
  modalNombre: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--text-principal)',
  },
  btnReservarModal: {
    padding: '13px',
    borderRadius: 'var(--radius-md)',
    border: 'none',
    background: 'var(--color-primario)',
    color: '#fff',
    fontWeight: 700,
    fontSize: 14,
    cursor: 'pointer',
    marginTop: 8,
    boxShadow: '0 4px 16px rgba(79, 70, 229, 0.3)',
  },
  btnCancelarModal: {
    padding: '13px',
    borderRadius: 'var(--radius-md)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    background: 'rgba(239, 68, 68, 0.1)',
    color: 'var(--color-error)',
    fontWeight: 700,
    fontSize: 14,
    cursor: 'pointer',
    marginTop: 8,
  },
  // Lightbox
  lightboxOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.95)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 200,
    cursor: 'pointer',
  },
  lightboxImg: {
    maxWidth: '95%',
    maxHeight: '85%',
    objectFit: 'contain',
    cursor: 'default',
    borderRadius: 'var(--radius-md)',
  },
  lightboxCerrar: {
    position: 'absolute',
    top: 16,
    right: 16,
    background: 'rgba(255,255,255,0.15)',
    backdropFilter: 'blur(10px)',
    color: '#fff',
    border: '1px solid rgba(255,255,255,0.2)',
    fontSize: 18,
    fontWeight: 700,
    width: 44,
    height: 44,
    borderRadius: 'var(--radius-full)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxNav: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'rgba(255,255,255,0.15)',
    backdropFilter: 'blur(10px)',
    color: '#fff',
    border: '1px solid rgba(255,255,255,0.2)',
    fontSize: 28,
    fontWeight: 700,
    width: 52,
    height: 52,
    borderRadius: 'var(--radius-full)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxContador: {
    position: 'absolute',
    bottom: 24,
    color: '#fff',
    fontSize: 13,
    fontWeight: 600,
    background: 'rgba(0,0,0,0.5)',
    padding: '6px 14px',
    borderRadius: 'var(--radius-full)',
  },
};

export default styles;